-- Allow employee_documents rows that live in SharePoint instead of Supabase Storage.
-- NDA files generated by the app are now uploaded to the Legal7 SharePoint folder;
-- we store the SharePoint webUrl in external_url (storage_path stays NULL for those).
-- Run this once in Supabase Dashboard → SQL Editor.

alter table employee_documents add column if not exists external_url text;
alter table employee_documents add column if not exists source text not null default 'supabase';
-- SharePoint-only docs have no Supabase storage key.
alter table employee_documents alter column storage_path drop not null;
